"""
Django settings for dailyfresh project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vqakr7%yvx5j1v**s0pnsgn=iu_e2pw+#7g8^(f7=l83uul459'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'haystack',
    'user',
    'cart',
    'goods',
    'order'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dailyfresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dailyfresh.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dailyfresh',
        'HOST': '127.0.0.1',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'PORT': 3306
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


#指定django认证系统使用自定义user model类
AUTH_USER_MODEL = 'user.User'

TINYMCE_DEFAULT_CONFIG = {
    'theme': 'advanced',
    'width': 600,
    'height': 400
}

EMAIL_ENGINE = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '673721260@qq.com'
EMAIL_HOST_PASSWORD = 'ggozxwvjqrvzbbbb'
EMAIL_FROM = '天天生鲜<673721260@qq.com>'

#设置缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            #"CONNECTION_POOL_KWARGS": {"max_connections": 100}

        }
    }
}

#设置session保存在redis缓存中，默认是保存在数据库中
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

LOGIN_URL = '/user/login'

#NGINX服务器地址
FDFS_NGINX_URL = 'http://192.168.1.13:8888/'
FDFS_CLIENT_CONF = os.path.join(BASE_DIR, 'utils/client.conf')

DEFAULT_FILE_STORAGE = 'utils.fdfs_storage.FdfsStorage'

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index')
    }
}

# 当添加、修改、删除数据时，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

ALIPAY_APPID = '2016101600698733'
ALIPAY_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmWKGE77+tkPIioRIEru8HIc2k1c6hXgGtjU0Xi6vxE/mh2tHjJqt57WrM08dBLzVqo+pAvBjukkYvWgvBuUtmObN6EHENtw7uyjersPBx8ysWZWkyFUvlDvN6BskImwomPWpMzSc6eK1Tj2XdfOxqsaDmcw4px2SSkq+HqYAe56YYno7kUapR1bzbOLjjw8BXHEvEaN0sYLcZqlNBCBvKgaTydR0m/cWN75edZNi0hKp0iWZxD3hFCWqgs/F7JP9lDyy/yDPM79kF5zFaxqN9+eC8/HmQMAgzPAgEnuoAl3JI/S9tg85GwpNNBfvv/vuoCuhGIGSSFiWwFci9oFKlwIDAQAB'
APP_PRIVATE_KEY = 'MIIEowIBAAKCAQEApXAYBqcv1Ud055ZXqQXptu64HZukv3SLwoehHcBZPoCv/N8DR4sAUa0JbkY4NXUdzhPfYhlxRaqByNRTGevk5gNb+/Geh22CKqcOYh/ewpcikhAHSYkvNfivqm5koFZLQXgdjGcY/dT4YD8K8aewVIwbyfSwvQ3nBFKo+hxFwTzXdlxGbO3vleWTHKWe2CZQTp//hrTNnmIvQPCSObcSOTwf31eyv2+nDH348Rl5GIygX2m7FG+7kPDrCmb3tx+ZOxJ5Rj79OpmkDKzHJz1YlPVE8KQTl/Xh5wjgkP8PGilr0yV2hzNn83QgUrSWunZQVvyTMkbZyvjDDJKvQ7ZWXwIDAQABAoIBAD2Q8o//RdDEL+BDVcoD9k7qlcAG/Q92ytAQ80eEHnIhJ90eDTVhqDO9BmZwYVibhgT75kS2nS3E31mikm5yGBP1KhUffNR/T1KaKsMfgyG9ZtMefefC0rvuGUl+nZoBoy3xCmYGtAk6aVg//c2ijv9XyLumgONKOi+kp1e0j8zyQh0OkUuSAeTxb7A2z6R7Y/IrYiXMnvpfcf+RjN1u8IvcVvIZ8nefqVkPIH3QN2XQc5mOel+zqZWQeYiXLsYGk8qw35xvrbJ7oHf29D19PlIkUIZt5zD0G0VUzOIY2cjI9Keto2JLnQ6bRizn+4JbneWi18bB/0ZBj4LhmhxSZkECgYEA6ET58huERz7N+Pmquzn1rwIZGE3kmrTKQGcKZf9LXeGWKSi/erAdwoq2HNGNC7DwZIqKtUElU8oluMXLH0SBu6dPCNSiOGLfwB4M4mUqmFfUEYzkAKUcmqhKaVW8yrqmZMRaUrFyiBIRR+uKSGhq+BEAW2LRu/agh/HGvFS2a2ECgYEAtlciC33aFMJqcdK34Xk7N3IssVH/NGcuGmFR1MggQW2r1VRj4JYStCmwVNLSaoHie5D/8MyFHrfgpnbGUjdBTGr019+Xj60Ql525LXaDnJaokUtaEpqPK5/F8pEc4TH1p9ZJn2FAnRlhtBf07TwFcW5QziVdDuE3EyPFIFT32b8CgYEA5ul8G6gjj7juiLGdfNkYWU6aqED4Hp3R3MkT22c9BC57XJv4EP759yhz+J6TvKXBuBLL53rGo1B6xAFP+NvgpjClMEBErg4OKC832/N7r0zRtkj9e26qy063+5STRnDdb5yNt1xWYtSjfX67UVUN02UDl9bccCO2YLCLRTxqxsECgYBg0oPRdlKHE3VSW4IoyCcZmhcBUXkiamegumypgFsgYwwLi3Q9nXLxF/H6GLiCtdV9p9FAHFnTpfA0dH16yrxxx5mbx67DLDLTT301FulsDNQV0t1RY6ECmSSTWVrseYroRHFzoECfKwsmhlIYZva89McTr+NqM0z7bNMQCA5UIQKBgCJzACJxJIr8tH6OHE/g6VzXhVzu7IbTITB1ASqyrl1pkwDdMHweIDPZdJCWZh0cJrSwKFzMgWGz66R7uouKw1SBuUR2IuyuOg1wSfHhd0DJDN6zFYlKzDVvu1Y66ZnavWnIPzwpehf0qRzaHhM2uRSBu2j7pCoZKYA8P4dvWxX1'
ALIPAY_SERVER_URL = 'https://openapi.alipaydev.com/gateway.do'