# Generated by Django 2.2.6 on 2019-11-04 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20191105_0105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '微信支付'), (3, '支付宝支付'), (4, '银联支付')], default=3, verbose_name='支付方式')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态')),
                ('total_count', models.IntegerField(default=1, verbose_name='购买数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价')),
                ('transfer_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费')),
                ('trade_no', models.CharField(max_length=128, verbose_name='支付编号')),
                ('address', models.ForeignKey(on_delete=None, to='user.Address', verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'df_order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('count', models.IntegerField(default=1, verbose_name='购买数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买单价')),
                ('comments', models.CharField(max_length=256, verbose_name='评论')),
                ('goods', models.ForeignKey(on_delete=None, to='goods.GoodsSKU', verbose_name='商品SKU')),
                ('order', models.ForeignKey(on_delete=None, to='order.OrderInfo', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
                'db_table': 'df_order_goods',
            },
        ),
    ]
